name: Build

on:
  pull_request:

jobs:
  build:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.JS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn install

      - name: Lint Project
        run: npm run lint

      - name: Build Project
        run: npm run build
